version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Europe/London"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "chalk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node-persist"
        update-types: ["version-update:semver-major"]
